#!/usr/bin/env python3
"""Run rungs 0-3, stop at the first failure, and retain review artifacts.

Rung 0 is trace mechanics.  Rungs 1-3 execute real integrate-and-fire circuits
(``ladder/spiking.py``) and are hand-checked by an independent pair-sum checker
(``ladder/handcheck.py``) from the recorded spike times.
"""

from __future__ import annotations

import csv
import json
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path

import matplotlib.pyplot as plt

from ladder.experiments import run_all_rungs

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "results_ladder"
COMMAND = "python run_ladder.py"


def _git_sha() -> str:
    return subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()


def _dirty() -> bool:
    out = subprocess.check_output(["git", "status", "--porcelain", "--", "ladder", "run_ladder.py"], cwd=ROOT, text=True)
    return bool(out.strip())


def _write_delay_csv(payload):
    path = OUT / "rung0_delay_credit.csv"
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=("tau_elig_ms", "delay_ms", "observed_credit", "theory_credit", "absolute_error"),
            lineterminator="\n",
        )
        writer.writeheader()
        for tau, curve in payload["results"]["rung_0"]["curves"].items():
            for row in curve["points"]:
                writer.writerow({"tau_elig_ms": tau, **row})


def _plot_delay(payload):
    fig, axes = plt.subplots(1, 3, figsize=(13, 4), sharey=True)
    for axis, (tau, curve) in zip(axes, payload["results"]["rung_0"]["curves"].items()):
        x = [row["delay_ms"] for row in curve["points"]]
        y = [row["observed_credit"] for row in curve["points"]]
        theory = [row["theory_credit"] for row in curve["points"]]
        noise = curve["noise_floor"]["noise_rms_normalized_to_unit_tag"]
        axis.semilogy(x, y, "o", label="measured")
        axis.semilogy(x, theory, "-", label="exp(-delay/tau)")
        axis.axhline(noise, color="tab:red", linestyle=":", label="5 Hz background RMS")
        axis.set_title(f"tau = {tau} ms")
        axis.set_xlabel("reward delay (ms)")
        axis.grid(True, alpha=0.25)
    axes[0].set_ylabel("credited fraction (log scale)")
    axes[-1].legend(fontsize=8)
    fig.suptitle("One tag fades continuously; it does not switch off")
    fig.tight_layout()
    fig.savefig(OUT / "rung0_delay_vs_credit.png", dpi=180)
    plt.close(fig)


def _gate_lines(result):
    return [f"  - {'PASS' if ok else 'FAIL'}: `{name}`" for name, ok in result.get("gates", {}).items()]


def _write_report(payload):
    r = payload["results"]
    lines = [
        "# R-STDP learning ladder: rungs 0-3 (executed circuits)",
        "",
        f"Generated: {payload['generated_at']}",
        f"Code commit: `{payload['code_commit']}` (ladder working tree dirty: {payload['code_dirty']})",
        f"Command: `{payload['command']}`  Wall time: {payload['wall_seconds']:.0f} s",
        f"Engine: {payload['engine']}",
        "",
        "Supersedes the synthetic rungs 1-3 of commit eb972c7. Nora's review t_a0a9775c rejected those because their eligibility vectors were preassigned and behavior was measured with a separate threshold probe.",
        "",
        "## Result table",
        "",
        "| Rung | Mechanism | Outcome | Gate |",
        "|---|---:|---:|---:|",
    ]
    for i in range(4):
        row = r.get(f"rung_{i}")
        if row is None:
            lines.append(f"| {i} | NOT RUN | NOT RUN | STOPPED |")
        else:
            lines.append(
                f"| {i} | {'PASS' if row['mechanism_pass'] else 'FAIL'} | "
                f"{'PASS' if row['outcome_pass'] else 'FAIL'} | {row['status']} |"
            )
    lines += [
        "",
        "## How each rung is measured",
        "",
        "- Circuits are integrate-and-fire neurons (rest/reset -70 mV, threshold -54 mV, tau_m 20 ms, Florian eq. 4.1). Each synapse is a direct voltage jump on the next 1 ms step. Plasticity is MSTDPET: A+=1, A-=-1, tau+=tau-=20 ms, tau_z=25 ms, gamma=0.2 mV, bounds [0, 20] mV. Input neurons fire Poisson spikes. Every output spike is generated by the simulation.",
        "- Reward is computed from spikes the circuit actually emitted and delivered on the next step plus any extra delay. Random-reward controls use an exogenous schedule with the same number of events.",
        "- Mechanism: `ladder/handcheck.py` shares no code with the simulator. It recomputes every weight at every millisecond from the recorded spike times, using explicit pair sums, and it rebuilds the reward schedule from the recorded spikes. It then replays every integrate-and-fire spike from the recorded inputs and its own hand-computed weights. Pass requires weight error < 1e-9 mV, zero spike mismatches, and an exact reward-schedule match.",
        "- Outcome: learned weights and a frozen copy with the initial weights are driven by the same held-out input panel (10 s, a new random seed). Firing is counted at the motif output.",
        "- `tests/test_ladder_executed.py` shows the checker fails when the simulator is deliberately broken: STDP sign flipped, reward one step late, reward applied before the eligibility update, synapse wiring crossed, and plasticity applied to every synapse regardless of eligibility.",
        "",
    ]
    for i in range(1, 4):
        row = r.get(f"rung_{i}")
        if row is not None:
            lines += [f"### Rung {i} gates", ""] + _gate_lines(row) + [""]
    r1 = r.get("rung_1")
    if r1 is not None:
        ra = r1["runaway_and_baseline"]
        lines += [
            "### Rung 1: runaway and baseline (reported, not gated)",
            "",
            f"- Raw self-reward reached the 20 mV bound on {ra['raw_self_reward_hit_bound_seeds']}/{len(ra['raw_first_ms_at_bound'])} seeds within 60 s; median weight every 10 s: {[round(x, 2) for x in ra['raw_weight_every_10s_mv_median']]} mV.",
            f"- Expected-reward baseline (r = f_out - running mean, tau 1 s) reached the bound on {ra['baseline_subtracted_hit_bound_seeds']}/{len(ra['baseline_first_ms_at_bound'])} seeds; median weight every 10 s: {[round(x, 2) for x in ra['baseline_weight_every_10s_mv_median']]} mV.",
            f"- {ra['note']}",
            "- Silence mirror: when the output never fires, positive reward on silent steps produces exactly zero weight change, because pair-based R-STDP only tags when a post spike occurs. Reward on silent steps while the output does sometimes fire raised the weight instead (arm `reward_every_silent_step`). The shrink test therefore punishes emitted spikes (arm `punish_emitted_spikes`), which is a different operationalization from rewarding silence.",
            "",
        ]
    r3 = r.get("rung_3")
    if r3 is not None:
        d = r3["disconnected_but_active_synapse"]
        lines += [
            "### Rung 3: an active but disconnected synapse",
            "",
            f"- D->E has no path to the rewarded output C, but D and E fire together. Its change under output-contingent reward was {[round(x, 2) for x in d['reward_on_output_delta_w_D_E_mv']]} mV. Under time-shuffled reward it was {[round(x, 2) for x in d['time_shuffled_delta_w_D_E_mv']]} mV.",
            f"- {d['interpretation']}",
            "- A disconnected synapse that is never eligible (D->F, subthreshold) stays exactly unchanged under every arm. The output C is bit-identical whatever the disconnected weights are.",
            "",
        ]
    lines += [
        "## Track 1 correction (unchanged)",
        "",
        "Track 1's NULL is a NULL for our old protocol, not for Florian's mechanism. The old protocol rewarded once, after a 500 ms trial. It used two outputs with an argmax readout, redrew the temporal input on every trial, reset the traces each trial, filtered the synaptic currents, and used different bounds and STDP scales. See `docs/FLORIAN_DIFFERENCE_TABLE.md`.",
    ]
    (OUT / "LADDER_REPORT.md").write_text("\n".join(lines) + "\n")


def main():
    OUT.mkdir(exist_ok=True)
    start = time.time()
    payload = run_all_rungs()
    payload.update(
        {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "code_commit": _git_sha(),
            "code_dirty": _dirty(),
            "command": COMMAND,
            "host": "Mac Mini",
            "engine": "rung 0: numpy trace reference (+ torch core decay cross-checked in tests); rungs 1-3: executed IF circuits ladder/spiking.py, independently hand-checked by ladder/handcheck.py",
            "wall_seconds": time.time() - start,
            "no_oracle_statement": "Rewards are computed only from spikes the circuit emitted (or from an exogenous random schedule in controls); no expected answer enters weights or spikes. Hand expectations are computed after the run from recorded spikes.",
        }
    )
    (OUT / "summary.json").write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    _write_delay_csv(payload)
    _plot_delay(payload)
    _write_report(payload)
    for name, result in payload["results"].items():
        print(f"{name}: mechanism={result['mechanism_pass']} outcome={result['outcome_pass']} gate={result['status']}")
    print(f"overall: {payload['status']}  wall={payload['wall_seconds']:.0f}s")
    print(f"artifacts: {OUT}")
    return 0 if payload["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
